[package]
name = "rust_aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
ureq = "2.3.1"
dotenv = "0.15.0"
colored = "2.0.0"
rand = "0.8.4"
rayon = "1.5.1"
