[package]
name = "rust_aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.1"
reqwest = { version = "0.11.2", features = ["blocking"] }
dotenv = "0.15.0"
